# Build the project with Meson
name: meson-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meson-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: --verbose
          meson-version: 1.2.3
      - name: Meson Build
        run: |
          mkdir build
          cd build
          meson compile
