# Build the project with Meson
name: meson-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meson-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This is my Personal Access Token to my fork of Ashvin's QuickMRC
          token: ${{ secrets.ASHVINGOEL_QUICKMRC_PAT_FOR_ONLINEMRC }}
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install meson ninja
      # Get Boost C++ library
      - run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install libboost-dev
      - run: meson setup builddir/
        env:
          CC: gcc
      - run: meson test -C builddir/ -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
