# Build the project with Meson
name: meson-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meson-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This is my Personal Access Token to my fork of Ashvin's QuickMRC
          token: ${{ secrets.ASHVINGOEL_QUICKMRC_PAT_FOR_ONLINEMRC }}
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install meson ninja
      - run: BOOST_ROOT=${{github.workspace}}
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
            # REQUIRED: Specify the required boost version
            # A list of supported versions can be found here:
            # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
            boost_version: 1.84.0
            # OPTIONAL: Specify a platform version
            platform_version: 22.04
            # OPTIONAL: Specify a custom install location
            boost_install_dir: ${{github.workspace}}
            # OPTIONAL: Specify a toolset
            toolset: gcc
            # OPTIONAL: Specify an architecture
            arch: x86
            # NOTE: If a boost version matching all requirements cannot be found,
            # this build step will fail
      - run: meson setup builddir/
        env:
          CC: gcc
      - run: meson test -C builddir/ -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
