# Build the project with Meson
name: meson-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meson-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: --verbose
          meson-version: 1.2.3
