# Build the project with Meson
name: meson-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meson-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install meson ninja
      - run: meson setup builddir/
        env:
          CC: gcc
      - run: meson test -C builddir/ -v
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
